const twilio = require('twilio');
require('dotenv').config();

const { 
  TWILIO_ACCOUNT_SID, 
  TWILIO_API_KEY_SID, 
  TWILIO_API_SECRET,
  TWILIO_TWIML_APP_SID 
} = process.env;

const client = twilio(TWILIO_API_KEY_SID, TWILIO_API_SECRET, { accountSid: TWILIO_ACCOUNT_SID });

// The URL generated by localhost.run
const PUBLIC_URL = 'https://2bc10d393baa2e.lhr.life';

async function updateTwiMLApp() {
  if (!TWILIO_TWIML_APP_SID) {
    console.log("No TwiML App SID found in .env. Skipping auto-update.");
    return;
  }

  try {
    console.log(`Updating TwiML App ${TWILIO_TWIML_APP_SID} with URL: ${PUBLIC_URL}/api/voice/outgoing`);
    
    await client.applications(TWILIO_TWIML_APP_SID).update({
      voiceUrl: `${PUBLIC_URL}/api/voice/outgoing`,
      voiceMethod: 'POST',
      voiceFallbackUrl: `${PUBLIC_URL}/api/voice/outgoing`,
      voiceFallbackMethod: 'POST'
    });
    
    console.log("SUCCESS! Twilio TwiML App update request sent.");

    // Verification Step
    const app = await client.applications(TWILIO_TWIML_APP_SID).fetch();
    console.log("--- CURRENT TWilio CONFIG ---");
    console.log("Voice URL:", app.voiceUrl);
    console.log("Fallback URL:", app.voiceFallbackUrl);
    
    if (app.voiceUrl.includes(PUBLIC_URL)) {
      console.log("✅ VERIFIED: Twilio is now pointing to your new tunnel.");
    } else {
      console.log("❌ ERROR: Twilio configuration mismatch detected!");
    }
  } catch (err) {
    console.error("Failed to update Twilio TwiML App:", err.message);
    console.log("Please update it manually in the Twilio Console to:", `${PUBLIC_URL}/api/voice/outgoing`);
  }
}

updateTwiMLApp();
